[INTER-544] Revisit
fingerprintjs/fingerprint-pro-server-api-php-sdk pull request #88
Opened 2024-03-20 07:03 UTC by TheUnderScorer

2024-03-21 09:41 UTC, Orkuncakilkaya approved these changes

2024-03-21 15:55 UTC, ilfa requested changes
Update please functional tests to use reusable workflow to report test status and to do it in one message instead of how is it configured now (separate message for each version).

2024-03-21 15:55 UTC, ilfa commented on .github/workflows/release.yml
> +      GH_RELEASE_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
We need to migrate to GH App

2024-03-22 08:59 UTC, TheUnderScorer commented on .github/workflows/release.yml
> +      GH_RELEASE_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
Done!

2024-03-22 15:06 UTC, ilfa requested changes

2024-03-22 15:06 UTC, ilfa commented on .github/workflows/test.yml
>        - uses: actions/checkout@v2
Here is still an old version.

2024-03-25 05:01 UTC, TheUnderScorer commented on .github/workflows/test.yml
>        - uses: actions/checkout@v2
Whoops, fixed!

2024-03-25 12:48 UTC, ilfa submitted a review, later dismissed

2024-03-25 14:35 UTC, ilfa requested changes

2024-03-25 14:35 UTC, ilfa commented on README.md
>      <a href="https://github.com/fingerprintjs/fingerprint-pro-server-api-php-sdk/actions/workflows/release.yml">
We need to fix formatting issues
![image](https://github.com/fingerprintjs/fingerprint-pro-server-api-php-sdk/assets/1009415/44a9524a-16c9-47bd-b071-2f9dd19f9c01)

2024-03-25 14:46 UTC, ilfa requested changes

2024-03-25 14:46 UTC, ilfa commented on .github/workflows/functional.yml
> +    needs: tests
```suggestion
    needs: functional_tests
```

2024-03-25 14:46 UTC, ilfa commented on .github/workflows/functional.yml
> +      job_status: ${{ needs.tests.result }}
```suggestion
      job_status: ${{ needs.functional_tests.result }}
```

2024-03-26 09:47 UTC, ilfa approved these changes

2024-03-26 11:28 UTC, merged